/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solid;

import solid.l.Dog;
import solid.l.Elephant;
import solid.s.Store;
import solid.s.StorePrinter;

/**
 *
 * @author isaac
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        printConsoleButton = new javax.swing.JButton();
        printRowsButton = new javax.swing.JButton();
        printOneRowButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        vehicleComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        drawButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        walkDogButton = new javax.swing.JButton();
        walkElephantButton = new javax.swing.JButton();
        jumpDogButton = new javax.swing.JButton();
        jumpElephantButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productComboBox = new javax.swing.JComboBox<>();
        infoButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paymentComboBox = new javax.swing.JComboBox<>();
        payButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Principio de Responsabilidad Única ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("Imprimir información de Tienda");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        printConsoleButton.setText("Imprimir en consola");
        printConsoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printConsoleButtonActionPerformed(evt);
            }
        });
        jPanel2.add(printConsoleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        printRowsButton.setText("Imprimir en varias filas");
        printRowsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRowsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(printRowsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        printOneRowButton.setText("imprimir en una fila");
        printOneRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printOneRowButtonActionPerformed(evt);
            }
        });
        jPanel2.add(printOneRowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jTabbedPane2.addTab("S", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Principio de Abierto/Cerrado ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        vehicleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Camión" }));
        jPanel3.add(vehicleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Planos de vehículos");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        drawButton.setText("Dibujar");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });
        jPanel3.add(drawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jTabbedPane2.addTab("O", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Principio de Sustitución de Liskov  ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Elefante");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Acciones de los animales");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Perro");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        walkDogButton.setText("Caminar");
        walkDogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkDogButtonActionPerformed(evt);
            }
        });
        jPanel4.add(walkDogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        walkElephantButton.setText("Caminar");
        walkElephantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkElephantButtonActionPerformed(evt);
            }
        });
        jPanel4.add(walkElephantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jumpDogButton.setText("Saltar un charco de agua");
        jumpDogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumpDogButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jumpDogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 20));

        jumpElephantButton.setText("Saltar un charco de agua");
        jumpElephantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumpElephantButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jumpElephantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jTabbedPane2.addTab("L", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Principio de Segregación de la Interfaz ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Inventario de Isaac's electronics");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        productComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "GameBoy", "BlueRay", "PSP" }));
        jPanel5.add(productComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 160, -1));

        infoButton.setText("Ver info");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });
        jPanel5.add(infoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jTabbedPane2.addTab("I", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Principio de Inversión de la Dependencia ");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Gracias por su compra! seleccione el método de pago: ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        paymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paypal", "Tarjeta de crédito", "Tarjeta de débito", "Pago móvil" }));
        paymentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentComboBoxActionPerformed(evt);
            }
        });
        jPanel6.add(paymentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 170, -1));

        payButton.setText("Pagar");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        jPanel6.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jTabbedPane2.addTab("D", jPanel6);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentComboBoxActionPerformed

    }//GEN-LAST:event_paymentComboBoxActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        Main.getApp().getPaymentForm(paymentComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_payButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        Main.getApp().getProduct(productComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_infoButtonActionPerformed

    private void walkDogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkDogButtonActionPerformed
       Main.getApp().getAnimalToWalk("Perro");
    }//GEN-LAST:event_walkDogButtonActionPerformed

    private void walkElephantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkElephantButtonActionPerformed
        Main.getApp().getAnimalToWalk("Elefante");
    }//GEN-LAST:event_walkElephantButtonActionPerformed

    private void jumpDogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumpDogButtonActionPerformed
        Dog dog = new Dog();
        Main.getApp().jumpLigthAnimal(dog);
    }//GEN-LAST:event_jumpDogButtonActionPerformed

    private void jumpElephantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumpElephantButtonActionPerformed
        Elephant elephant = new Elephant();
        Main.getApp().tryToJumpAnimal(elephant);
    }//GEN-LAST:event_jumpElephantButtonActionPerformed

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        Main.getApp().getVehicleToDraw(vehicleComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_drawButtonActionPerformed

    private void printConsoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printConsoleButtonActionPerformed
        Store store = new Store("Panaderia la Latina", "123", "El Marqués");
        StorePrinter printer = new StorePrinter(store);
        Main.getApp().printStoreInfo(printer, 0);
    }//GEN-LAST:event_printConsoleButtonActionPerformed

    private void printRowsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRowsButtonActionPerformed
       Store store = new Store("Panaderia la Latina", "123", "El Marqués");
        StorePrinter printer = new StorePrinter(store);
        Main.getApp().printStoreInfo(printer, 1);
    }//GEN-LAST:event_printRowsButtonActionPerformed

    private void printOneRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printOneRowButtonActionPerformed
        Store store = new Store("Panaderia la Latina", "123", "El Marqués");
        StorePrinter printer = new StorePrinter(store);
        Main.getApp().printStoreInfo(printer, 2);
    }//GEN-LAST:event_printOneRowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    public javax.swing.JComboBox<String> getPaymentComboBox() {
        return this.paymentComboBox;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drawButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jumpDogButton;
    private javax.swing.JButton jumpElephantButton;
    private javax.swing.JButton payButton;
    private javax.swing.JComboBox<String> paymentComboBox;
    private javax.swing.JButton printConsoleButton;
    private javax.swing.JButton printOneRowButton;
    private javax.swing.JButton printRowsButton;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JComboBox<String> vehicleComboBox;
    private javax.swing.JButton walkDogButton;
    private javax.swing.JButton walkElephantButton;
    // End of variables declaration//GEN-END:variables
}
